-- lua_iso_639 - a Lua module for working with ISO 639 language codes
-- copyright (c) 2025  Alex Rogers <https://github.com/linguisticmind>
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

-- Source:
--
-- Library of Congress. "Codes for the Representation of Names of Languages. ISO 639 codes arranged alphabetically by alpha-3 code: downloadable text files." Retrieved 2025-11-16.
-- <https://www.loc.gov/standards/iso639-2/ascii_8bits.html>
-- <https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt>
-- <https://www.loc.gov/standards/iso639-2/ISO-639-2_8859-1.txt>

local data = {

  ['aa'] = 'aar',
  ['aar'] = { iso_639_1 = 'aa', iso_639_2 = { b = 'aar' }, exonym = { ['eng'] = { 'Afar' }, ['fre'] = { 'afar' } } },
  ['ab'] = 'abk',
  ['abk'] = { iso_639_1 = 'ab', iso_639_2 = { b = 'abk' }, exonym = { ['eng'] = { 'Abkhazian' }, ['fre'] = { 'abkhaze' } } },
  ['ace'] = { iso_639_2 = { b = 'ace' }, exonym = { ['eng'] = { 'Achinese' }, ['fre'] = { 'aceh' } } },
  ['ach'] = { iso_639_2 = { b = 'ach' }, exonym = { ['eng'] = { 'Acoli' }, ['fre'] = { 'acoli' } } },
  ['ada'] = { iso_639_2 = { b = 'ada' }, exonym = { ['eng'] = { 'Adangme' }, ['fre'] = { 'adangme' } } },
  ['ady'] = { iso_639_2 = { b = 'ady' }, exonym = { ['eng'] = { 'Adyghe', 'Adygei' }, ['fre'] = { 'adyghé' } } },
  ['afa'] = { iso_639_2 = { b = 'afa' }, exonym = { ['eng'] = { 'Afro-Asiatic languages' }, ['fre'] = { 'afro-asiatiques, langues' } } },
  ['afh'] = { iso_639_2 = { b = 'afh' }, exonym = { ['eng'] = { 'Afrihili' }, ['fre'] = { 'afrihili' } } },
  ['af'] = 'afr',
  ['afr'] = { iso_639_1 = 'af', iso_639_2 = { b = 'afr' }, exonym = { ['eng'] = { 'Afrikaans' }, ['fre'] = { 'afrikaans' } } },
  ['ain'] = { iso_639_2 = { b = 'ain' }, exonym = { ['eng'] = { 'Ainu' }, ['fre'] = { 'aïnou' } } },
  ['ak'] = 'aka',
  ['aka'] = { iso_639_1 = 'ak', iso_639_2 = { b = 'aka' }, exonym = { ['eng'] = { 'Akan' }, ['fre'] = { 'akan' } } },
  ['akk'] = { iso_639_2 = { b = 'akk' }, exonym = { ['eng'] = { 'Akkadian' }, ['fre'] = { 'akkadien' } } },
  ['sq'] = 'alb',
  ['sqi'] = 'alb',
  ['alb'] = { iso_639_1 = 'sq', iso_639_2 = { b = 'alb', t = 'sqi' }, exonym = { ['eng'] = { 'Albanian' }, ['fre'] = { 'albanais' } } },
  ['ale'] = { iso_639_2 = { b = 'ale' }, exonym = { ['eng'] = { 'Aleut' }, ['fre'] = { 'aléoute' } } },
  ['alg'] = { iso_639_2 = { b = 'alg' }, exonym = { ['eng'] = { 'Algonquian languages' }, ['fre'] = { 'algonquines, langues' } } },
  ['alt'] = { iso_639_2 = { b = 'alt' }, exonym = { ['eng'] = { 'Southern Altai' }, ['fre'] = { 'altai du Sud' } } },
  ['am'] = 'amh',
  ['amh'] = { iso_639_1 = 'am', iso_639_2 = { b = 'amh' }, exonym = { ['eng'] = { 'Amharic' }, ['fre'] = { 'amharique' } } },
  ['ang'] = { iso_639_2 = { b = 'ang' }, exonym = { ['eng'] = { 'English, Old (ca.450-1100)' }, ['fre'] = { 'anglo-saxon (ca.450-1100)' } } },
  ['anp'] = { iso_639_2 = { b = 'anp' }, exonym = { ['eng'] = { 'Angika' }, ['fre'] = { 'angika' } } },
  ['apa'] = { iso_639_2 = { b = 'apa' }, exonym = { ['eng'] = { 'Apache languages' }, ['fre'] = { 'apaches, langues' } } },
  ['ar'] = 'ara',
  ['ara'] = { iso_639_1 = 'ar', iso_639_2 = { b = 'ara' }, exonym = { ['eng'] = { 'Arabic' }, ['fre'] = { 'arabe' } } },
  ['arc'] = { iso_639_2 = { b = 'arc' }, exonym = { ['eng'] = { 'Official Aramaic (700-300 BCE)', 'Imperial Aramaic (700-300 BCE)' }, ['fre'] = { 'araméen d\'empire (700-300 BCE)' } } },
  ['an'] = 'arg',
  ['arg'] = { iso_639_1 = 'an', iso_639_2 = { b = 'arg' }, exonym = { ['eng'] = { 'Aragonese' }, ['fre'] = { 'aragonais' } } },
  ['hy'] = 'arm',
  ['hye'] = 'arm',
  ['arm'] = { iso_639_1 = 'hy', iso_639_2 = { b = 'arm', t = 'hye' }, exonym = { ['eng'] = { 'Armenian' }, ['fre'] = { 'arménien' } } },
  ['arn'] = { iso_639_2 = { b = 'arn' }, exonym = { ['eng'] = { 'Mapudungun', 'Mapuche' }, ['fre'] = { 'mapudungun', 'mapuche', 'mapuce' } } },
  ['arp'] = { iso_639_2 = { b = 'arp' }, exonym = { ['eng'] = { 'Arapaho' }, ['fre'] = { 'arapaho' } } },
  ['art'] = { iso_639_2 = { b = 'art' }, exonym = { ['eng'] = { 'Artificial languages' }, ['fre'] = { 'artificielles, langues' } } },
  ['arw'] = { iso_639_2 = { b = 'arw' }, exonym = { ['eng'] = { 'Arawak' }, ['fre'] = { 'arawak' } } },
  ['as'] = 'asm',
  ['asm'] = { iso_639_1 = 'as', iso_639_2 = { b = 'asm' }, exonym = { ['eng'] = { 'Assamese' }, ['fre'] = { 'assamais' } } },
  ['ast'] = { iso_639_2 = { b = 'ast' }, exonym = { ['eng'] = { 'Asturian', 'Bable', 'Leonese', 'Asturleonese' }, ['fre'] = { 'asturien', 'bable', 'léonais', 'asturoléonais' } } },
  ['ath'] = { iso_639_2 = { b = 'ath' }, exonym = { ['eng'] = { 'Athapascan languages' }, ['fre'] = { 'athapascanes, langues' } } },
  ['aus'] = { iso_639_2 = { b = 'aus' }, exonym = { ['eng'] = { 'Australian languages' }, ['fre'] = { 'australiennes, langues' } } },
  ['av'] = 'ava',
  ['ava'] = { iso_639_1 = 'av', iso_639_2 = { b = 'ava' }, exonym = { ['eng'] = { 'Avaric' }, ['fre'] = { 'avar' } } },
  ['ae'] = 'ave',
  ['ave'] = { iso_639_1 = 'ae', iso_639_2 = { b = 'ave' }, exonym = { ['eng'] = { 'Avestan' }, ['fre'] = { 'avestique' } } },
  ['awa'] = { iso_639_2 = { b = 'awa' }, exonym = { ['eng'] = { 'Awadhi' }, ['fre'] = { 'awadhi' } } },
  ['ay'] = 'aym',
  ['aym'] = { iso_639_1 = 'ay', iso_639_2 = { b = 'aym' }, exonym = { ['eng'] = { 'Aymara' }, ['fre'] = { 'aymara' } } },
  ['az'] = 'aze',
  ['aze'] = { iso_639_1 = 'az', iso_639_2 = { b = 'aze' }, exonym = { ['eng'] = { 'Azerbaijani' }, ['fre'] = { 'azéri' } } },
  ['bad'] = { iso_639_2 = { b = 'bad' }, exonym = { ['eng'] = { 'Banda languages' }, ['fre'] = { 'banda, langues' } } },
  ['bai'] = { iso_639_2 = { b = 'bai' }, exonym = { ['eng'] = { 'Bamileke languages' }, ['fre'] = { 'bamiléké, langues' } } },
  ['ba'] = 'bak',
  ['bak'] = { iso_639_1 = 'ba', iso_639_2 = { b = 'bak' }, exonym = { ['eng'] = { 'Bashkir' }, ['fre'] = { 'bachkir' } } },
  ['bal'] = { iso_639_2 = { b = 'bal' }, exonym = { ['eng'] = { 'Baluchi' }, ['fre'] = { 'baloutchi' } } },
  ['bm'] = 'bam',
  ['bam'] = { iso_639_1 = 'bm', iso_639_2 = { b = 'bam' }, exonym = { ['eng'] = { 'Bambara' }, ['fre'] = { 'bambara' } } },
  ['ban'] = { iso_639_2 = { b = 'ban' }, exonym = { ['eng'] = { 'Balinese' }, ['fre'] = { 'balinais' } } },
  ['eu'] = 'baq',
  ['eus'] = 'baq',
  ['baq'] = { iso_639_1 = 'eu', iso_639_2 = { b = 'baq', t = 'eus' }, exonym = { ['eng'] = { 'Basque' }, ['fre'] = { 'basque' } } },
  ['bas'] = { iso_639_2 = { b = 'bas' }, exonym = { ['eng'] = { 'Basa' }, ['fre'] = { 'basa' } } },
  ['bat'] = { iso_639_2 = { b = 'bat' }, exonym = { ['eng'] = { 'Baltic languages' }, ['fre'] = { 'baltes, langues' } } },
  ['bej'] = { iso_639_2 = { b = 'bej' }, exonym = { ['eng'] = { 'Beja', 'Bedawiyet' }, ['fre'] = { 'bedja' } } },
  ['be'] = 'bel',
  ['bel'] = { iso_639_1 = 'be', iso_639_2 = { b = 'bel' }, exonym = { ['eng'] = { 'Belarusian' }, ['fre'] = { 'biélorusse' } } },
  ['bem'] = { iso_639_2 = { b = 'bem' }, exonym = { ['eng'] = { 'Bemba' }, ['fre'] = { 'bemba' } } },
  ['bn'] = 'ben',
  ['ben'] = { iso_639_1 = 'bn', iso_639_2 = { b = 'ben' }, exonym = { ['eng'] = { 'Bengali' }, ['fre'] = { 'bengali' } } },
  ['ber'] = { iso_639_2 = { b = 'ber' }, exonym = { ['eng'] = { 'Berber languages' }, ['fre'] = { 'berbères, langues' } } },
  ['bho'] = { iso_639_2 = { b = 'bho' }, exonym = { ['eng'] = { 'Bhojpuri' }, ['fre'] = { 'bhojpuri' } } },
  ['bih'] = { iso_639_2 = { b = 'bih' }, exonym = { ['eng'] = { 'Bihari languages' }, ['fre'] = { 'langues biharis' } } },
  ['bik'] = { iso_639_2 = { b = 'bik' }, exonym = { ['eng'] = { 'Bikol' }, ['fre'] = { 'bikol' } } },
  ['bin'] = { iso_639_2 = { b = 'bin' }, exonym = { ['eng'] = { 'Bini', 'Edo' }, ['fre'] = { 'bini', 'edo' } } },
  ['bi'] = 'bis',
  ['bis'] = { iso_639_1 = 'bi', iso_639_2 = { b = 'bis' }, exonym = { ['eng'] = { 'Bislama' }, ['fre'] = { 'bichlamar' } } },
  ['bla'] = { iso_639_2 = { b = 'bla' }, exonym = { ['eng'] = { 'Siksika' }, ['fre'] = { 'blackfoot' } } },
  ['bnt'] = { iso_639_2 = { b = 'bnt' }, exonym = { ['eng'] = { 'Bantu languages' }, ['fre'] = { 'bantou, langues' } } },
  ['bs'] = 'bos',
  ['bos'] = { iso_639_1 = 'bs', iso_639_2 = { b = 'bos' }, exonym = { ['eng'] = { 'Bosnian' }, ['fre'] = { 'bosniaque' } } },
  ['bra'] = { iso_639_2 = { b = 'bra' }, exonym = { ['eng'] = { 'Braj' }, ['fre'] = { 'braj' } } },
  ['br'] = 'bre',
  ['bre'] = { iso_639_1 = 'br', iso_639_2 = { b = 'bre' }, exonym = { ['eng'] = { 'Breton' }, ['fre'] = { 'breton' } } },
  ['btk'] = { iso_639_2 = { b = 'btk' }, exonym = { ['eng'] = { 'Batak languages' }, ['fre'] = { 'batak, langues' } } },
  ['bua'] = { iso_639_2 = { b = 'bua' }, exonym = { ['eng'] = { 'Buriat' }, ['fre'] = { 'bouriate' } } },
  ['bug'] = { iso_639_2 = { b = 'bug' }, exonym = { ['eng'] = { 'Buginese' }, ['fre'] = { 'bugi' } } },
  ['bg'] = 'bul',
  ['bul'] = { iso_639_1 = 'bg', iso_639_2 = { b = 'bul' }, exonym = { ['eng'] = { 'Bulgarian' }, ['fre'] = { 'bulgare' } } },
  ['my'] = 'bur',
  ['mya'] = 'bur',
  ['bur'] = { iso_639_1 = 'my', iso_639_2 = { b = 'bur', t = 'mya' }, exonym = { ['eng'] = { 'Burmese' }, ['fre'] = { 'birman' } } },
  ['byn'] = { iso_639_2 = { b = 'byn' }, exonym = { ['eng'] = { 'Blin', 'Bilin' }, ['fre'] = { 'blin', 'bilen' } } },
  ['cad'] = { iso_639_2 = { b = 'cad' }, exonym = { ['eng'] = { 'Caddo' }, ['fre'] = { 'caddo' } } },
  ['cai'] = { iso_639_2 = { b = 'cai' }, exonym = { ['eng'] = { 'Central American Indian languages' }, ['fre'] = { 'amérindiennes de L\'Amérique centrale, langues' } } },
  ['car'] = { iso_639_2 = { b = 'car' }, exonym = { ['eng'] = { 'Galibi Carib' }, ['fre'] = { 'karib', 'galibi', 'carib' } } },
  ['ca'] = 'cat',
  ['cat'] = { iso_639_1 = 'ca', iso_639_2 = { b = 'cat' }, exonym = { ['eng'] = { 'Catalan', 'Valencian' }, ['fre'] = { 'catalan', 'valencien' } } },
  ['cau'] = { iso_639_2 = { b = 'cau' }, exonym = { ['eng'] = { 'Caucasian languages' }, ['fre'] = { 'caucasiennes, langues' } } },
  ['ceb'] = { iso_639_2 = { b = 'ceb' }, exonym = { ['eng'] = { 'Cebuano' }, ['fre'] = { 'cebuano' } } },
  ['cel'] = { iso_639_2 = { b = 'cel' }, exonym = { ['eng'] = { 'Celtic languages' }, ['fre'] = { 'celtiques, langues', 'celtes, langues' } } },
  ['ch'] = 'cha',
  ['cha'] = { iso_639_1 = 'ch', iso_639_2 = { b = 'cha' }, exonym = { ['eng'] = { 'Chamorro' }, ['fre'] = { 'chamorro' } } },
  ['chb'] = { iso_639_2 = { b = 'chb' }, exonym = { ['eng'] = { 'Chibcha' }, ['fre'] = { 'chibcha' } } },
  ['ce'] = 'che',
  ['che'] = { iso_639_1 = 'ce', iso_639_2 = { b = 'che' }, exonym = { ['eng'] = { 'Chechen' }, ['fre'] = { 'tchétchène' } } },
  ['chg'] = { iso_639_2 = { b = 'chg' }, exonym = { ['eng'] = { 'Chagatai' }, ['fre'] = { 'djaghataï' } } },
  ['zh'] = 'chi',
  ['zho'] = 'chi',
  ['chi'] = { iso_639_1 = 'zh', iso_639_2 = { b = 'chi', t = 'zho' }, exonym = { ['eng'] = { 'Chinese' }, ['fre'] = { 'chinois' } } },
  ['chk'] = { iso_639_2 = { b = 'chk' }, exonym = { ['eng'] = { 'Chuukese' }, ['fre'] = { 'chuuk' } } },
  ['chm'] = { iso_639_2 = { b = 'chm' }, exonym = { ['eng'] = { 'Mari' }, ['fre'] = { 'mari' } } },
  ['chn'] = { iso_639_2 = { b = 'chn' }, exonym = { ['eng'] = { 'Chinook jargon' }, ['fre'] = { 'chinook, jargon' } } },
  ['cho'] = { iso_639_2 = { b = 'cho' }, exonym = { ['eng'] = { 'Choctaw' }, ['fre'] = { 'choctaw' } } },
  ['chp'] = { iso_639_2 = { b = 'chp' }, exonym = { ['eng'] = { 'Chipewyan', 'Dene Suline' }, ['fre'] = { 'chipewyan' } } },
  ['chr'] = { iso_639_2 = { b = 'chr' }, exonym = { ['eng'] = { 'Cherokee' }, ['fre'] = { 'cherokee' } } },
  ['cu'] = 'chu',
  ['chu'] = { iso_639_1 = 'cu', iso_639_2 = { b = 'chu' }, exonym = { ['eng'] = { 'Church Slavic', 'Old Slavonic', 'Church Slavonic', 'Old Bulgarian', 'Old Church Slavonic' }, ['fre'] = { 'slavon d\'église', 'vieux slave', 'slavon liturgique', 'vieux bulgare' } } },
  ['cv'] = 'chv',
  ['chv'] = { iso_639_1 = 'cv', iso_639_2 = { b = 'chv' }, exonym = { ['eng'] = { 'Chuvash' }, ['fre'] = { 'tchouvache' } } },
  ['chy'] = { iso_639_2 = { b = 'chy' }, exonym = { ['eng'] = { 'Cheyenne' }, ['fre'] = { 'cheyenne' } } },
  ['cmc'] = { iso_639_2 = { b = 'cmc' }, exonym = { ['eng'] = { 'Chamic languages' }, ['fre'] = { 'chames, langues' } } },
  ['cnr'] = { iso_639_2 = { b = 'cnr' }, exonym = { ['eng'] = { 'Montenegrin' }, ['fre'] = { 'monténégrin' } } },
  ['cop'] = { iso_639_2 = { b = 'cop' }, exonym = { ['eng'] = { 'Coptic' }, ['fre'] = { 'copte' } } },
  ['kw'] = 'cor',
  ['cor'] = { iso_639_1 = 'kw', iso_639_2 = { b = 'cor' }, exonym = { ['eng'] = { 'Cornish' }, ['fre'] = { 'cornique' } } },
  ['co'] = 'cos',
  ['cos'] = { iso_639_1 = 'co', iso_639_2 = { b = 'cos' }, exonym = { ['eng'] = { 'Corsican' }, ['fre'] = { 'corse' } } },
  ['cpe'] = { iso_639_2 = { b = 'cpe' }, exonym = { ['eng'] = { 'Creoles and pidgins, English based' }, ['fre'] = { 'créoles et pidgins basés sur l\'anglais' } } },
  ['cpf'] = { iso_639_2 = { b = 'cpf' }, exonym = { ['eng'] = { 'Creoles and pidgins, French-based' }, ['fre'] = { 'créoles et pidgins basés sur le français' } } },
  ['cpp'] = { iso_639_2 = { b = 'cpp' }, exonym = { ['eng'] = { 'Creoles and pidgins, Portuguese-based' }, ['fre'] = { 'créoles et pidgins basés sur le portugais' } } },
  ['cr'] = 'cre',
  ['cre'] = { iso_639_1 = 'cr', iso_639_2 = { b = 'cre' }, exonym = { ['eng'] = { 'Cree' }, ['fre'] = { 'cree' } } },
  ['crh'] = { iso_639_2 = { b = 'crh' }, exonym = { ['eng'] = { 'Crimean Tatar', 'Crimean Turkish' }, ['fre'] = { 'tatar de Crimé' } } },
  ['crp'] = { iso_639_2 = { b = 'crp' }, exonym = { ['eng'] = { 'Creoles and pidgins' }, ['fre'] = { 'créoles et pidgins' } } },
  ['csb'] = { iso_639_2 = { b = 'csb' }, exonym = { ['eng'] = { 'Kashubian' }, ['fre'] = { 'kachoube' } } },
  ['cus'] = { iso_639_2 = { b = 'cus' }, exonym = { ['eng'] = { 'Cushitic languages' }, ['fre'] = { 'couchitiques, langues' } } },
  ['cs'] = 'cze',
  ['ces'] = 'cze',
  ['cze'] = { iso_639_1 = 'cs', iso_639_2 = { b = 'cze', t = 'ces' }, exonym = { ['eng'] = { 'Czech' }, ['fre'] = { 'tchèque' } } },
  ['dak'] = { iso_639_2 = { b = 'dak' }, exonym = { ['eng'] = { 'Dakota' }, ['fre'] = { 'dakota' } } },
  ['da'] = 'dan',
  ['dan'] = { iso_639_1 = 'da', iso_639_2 = { b = 'dan' }, exonym = { ['eng'] = { 'Danish' }, ['fre'] = { 'danois' } } },
  ['dar'] = { iso_639_2 = { b = 'dar' }, exonym = { ['eng'] = { 'Dargwa' }, ['fre'] = { 'dargwa' } } },
  ['day'] = { iso_639_2 = { b = 'day' }, exonym = { ['eng'] = { 'Land Dayak languages' }, ['fre'] = { 'dayak, langues' } } },
  ['del'] = { iso_639_2 = { b = 'del' }, exonym = { ['eng'] = { 'Delaware' }, ['fre'] = { 'delaware' } } },
  ['den'] = { iso_639_2 = { b = 'den' }, exonym = { ['eng'] = { 'Slave (Athapascan)' }, ['fre'] = { 'esclave (athapascan)' } } },
  ['dgr'] = { iso_639_2 = { b = 'dgr' }, exonym = { ['eng'] = { 'Tlicho', 'Dogrib' }, ['fre'] = { 'tlicho', 'dogrib' } } },
  ['din'] = { iso_639_2 = { b = 'din' }, exonym = { ['eng'] = { 'Dinka' }, ['fre'] = { 'dinka' } } },
  ['dv'] = 'div',
  ['div'] = { iso_639_1 = 'dv', iso_639_2 = { b = 'div' }, exonym = { ['eng'] = { 'Divehi', 'Dhivehi', 'Maldivian' }, ['fre'] = { 'maldivien' } } },
  ['doi'] = { iso_639_2 = { b = 'doi' }, exonym = { ['eng'] = { 'Dogri' }, ['fre'] = { 'dogri' } } },
  ['dra'] = { iso_639_2 = { b = 'dra' }, exonym = { ['eng'] = { 'Dravidian languages' }, ['fre'] = { 'dravidiennes, langues' } } },
  ['dsb'] = { iso_639_2 = { b = 'dsb' }, exonym = { ['eng'] = { 'Lower Sorbian' }, ['fre'] = { 'bas-sorabe' } } },
  ['dua'] = { iso_639_2 = { b = 'dua' }, exonym = { ['eng'] = { 'Duala' }, ['fre'] = { 'douala' } } },
  ['dum'] = { iso_639_2 = { b = 'dum' }, exonym = { ['eng'] = { 'Dutch, Middle (ca.1050-1350)' }, ['fre'] = { 'néerlandais moyen (ca. 1050-1350)' } } },
  ['nl'] = 'dut',
  ['nld'] = 'dut',
  ['dut'] = { iso_639_1 = 'nl', iso_639_2 = { b = 'dut', t = 'nld' }, exonym = { ['eng'] = { 'Dutch', 'Flemish' }, ['fre'] = { 'néerlandais', 'flamand' } } },
  ['dyu'] = { iso_639_2 = { b = 'dyu' }, exonym = { ['eng'] = { 'Dyula' }, ['fre'] = { 'dioula' } } },
  ['dz'] = 'dzo',
  ['dzo'] = { iso_639_1 = 'dz', iso_639_2 = { b = 'dzo' }, exonym = { ['eng'] = { 'Dzongkha' }, ['fre'] = { 'dzongkha' } } },
  ['efi'] = { iso_639_2 = { b = 'efi' }, exonym = { ['eng'] = { 'Efik' }, ['fre'] = { 'efik' } } },
  ['egy'] = { iso_639_2 = { b = 'egy' }, exonym = { ['eng'] = { 'Egyptian (Ancient)' }, ['fre'] = { 'égyptien' } } },
  ['eka'] = { iso_639_2 = { b = 'eka' }, exonym = { ['eng'] = { 'Ekajuk' }, ['fre'] = { 'ekajuk' } } },
  ['elx'] = { iso_639_2 = { b = 'elx' }, exonym = { ['eng'] = { 'Elamite' }, ['fre'] = { 'élamite' } } },
  ['en'] = 'eng',
  ['eng'] = { iso_639_1 = 'en', iso_639_2 = { b = 'eng' }, exonym = { ['eng'] = { 'English' }, ['fre'] = { 'anglais' } } },
  ['enm'] = { iso_639_2 = { b = 'enm' }, exonym = { ['eng'] = { 'English, Middle (1100-1500)' }, ['fre'] = { 'anglais moyen (1100-1500)' } } },
  ['eo'] = 'epo',
  ['epo'] = { iso_639_1 = 'eo', iso_639_2 = { b = 'epo' }, exonym = { ['eng'] = { 'Esperanto' }, ['fre'] = { 'espéranto' } } },
  ['et'] = 'est',
  ['est'] = { iso_639_1 = 'et', iso_639_2 = { b = 'est' }, exonym = { ['eng'] = { 'Estonian' }, ['fre'] = { 'estonien' } } },
  ['ee'] = 'ewe',
  ['ewe'] = { iso_639_1 = 'ee', iso_639_2 = { b = 'ewe' }, exonym = { ['eng'] = { 'Ewe' }, ['fre'] = { 'éwé' } } },
  ['ewo'] = { iso_639_2 = { b = 'ewo' }, exonym = { ['eng'] = { 'Ewondo' }, ['fre'] = { 'éwondo' } } },
  ['fan'] = { iso_639_2 = { b = 'fan' }, exonym = { ['eng'] = { 'Fang' }, ['fre'] = { 'fang' } } },
  ['fo'] = 'fao',
  ['fao'] = { iso_639_1 = 'fo', iso_639_2 = { b = 'fao' }, exonym = { ['eng'] = { 'Faroese' }, ['fre'] = { 'féroïen' } } },
  ['fat'] = { iso_639_2 = { b = 'fat' }, exonym = { ['eng'] = { 'Fanti' }, ['fre'] = { 'fanti' } } },
  ['fj'] = 'fij',
  ['fij'] = { iso_639_1 = 'fj', iso_639_2 = { b = 'fij' }, exonym = { ['eng'] = { 'Fijian' }, ['fre'] = { 'fidjien' } } },
  ['fil'] = { iso_639_2 = { b = 'fil' }, exonym = { ['eng'] = { 'Filipino', 'Pilipino' }, ['fre'] = { 'filipino', 'pilipino' } } },
  ['fi'] = 'fin',
  ['fin'] = { iso_639_1 = 'fi', iso_639_2 = { b = 'fin' }, exonym = { ['eng'] = { 'Finnish' }, ['fre'] = { 'finnois' } } },
  ['fiu'] = { iso_639_2 = { b = 'fiu' }, exonym = { ['eng'] = { 'Finno-Ugrian languages' }, ['fre'] = { 'finno-ougriennes, langues' } } },
  ['fon'] = { iso_639_2 = { b = 'fon' }, exonym = { ['eng'] = { 'Fon' }, ['fre'] = { 'fon' } } },
  ['fr'] = 'fre',
  ['fra'] = 'fre',
  ['fre'] = { iso_639_1 = 'fr', iso_639_2 = { b = 'fre', t = 'fra' }, exonym = { ['eng'] = { 'French' }, ['fre'] = { 'français' } } },
  ['frm'] = { iso_639_2 = { b = 'frm' }, exonym = { ['eng'] = { 'French, Middle (ca.1400-1600)' }, ['fre'] = { 'français moyen (1400-1600)' } } },
  ['fro'] = { iso_639_2 = { b = 'fro' }, exonym = { ['eng'] = { 'French, Old (842-ca.1400)' }, ['fre'] = { 'français ancien (842-ca.1400)' } } },
  ['frr'] = { iso_639_2 = { b = 'frr' }, exonym = { ['eng'] = { 'Northern Frisian' }, ['fre'] = { 'frison septentrional' } } },
  ['frs'] = { iso_639_2 = { b = 'frs' }, exonym = { ['eng'] = { 'Eastern Frisian' }, ['fre'] = { 'frison oriental' } } },
  ['fy'] = 'fry',
  ['fry'] = { iso_639_1 = 'fy', iso_639_2 = { b = 'fry' }, exonym = { ['eng'] = { 'Western Frisian' }, ['fre'] = { 'frison occidental' } } },
  ['ff'] = 'ful',
  ['ful'] = { iso_639_1 = 'ff', iso_639_2 = { b = 'ful' }, exonym = { ['eng'] = { 'Fulah' }, ['fre'] = { 'peul' } } },
  ['fur'] = { iso_639_2 = { b = 'fur' }, exonym = { ['eng'] = { 'Friulian' }, ['fre'] = { 'frioulan' } } },
  ['gaa'] = { iso_639_2 = { b = 'gaa' }, exonym = { ['eng'] = { 'Ga' }, ['fre'] = { 'ga' } } },
  ['gay'] = { iso_639_2 = { b = 'gay' }, exonym = { ['eng'] = { 'Gayo' }, ['fre'] = { 'gayo' } } },
  ['gba'] = { iso_639_2 = { b = 'gba' }, exonym = { ['eng'] = { 'Gbaya' }, ['fre'] = { 'gbaya' } } },
  ['gem'] = { iso_639_2 = { b = 'gem' }, exonym = { ['eng'] = { 'Germanic languages' }, ['fre'] = { 'germaniques, langues' } } },
  ['ka'] = 'geo',
  ['kat'] = 'geo',
  ['geo'] = { iso_639_1 = 'ka', iso_639_2 = { b = 'geo', t = 'kat' }, exonym = { ['eng'] = { 'Georgian' }, ['fre'] = { 'géorgien' } } },
  ['de'] = 'ger',
  ['deu'] = 'ger',
  ['ger'] = { iso_639_1 = 'de', iso_639_2 = { b = 'ger', t = 'deu' }, exonym = { ['eng'] = { 'German' }, ['fre'] = { 'allemand' } } },
  ['gez'] = { iso_639_2 = { b = 'gez' }, exonym = { ['eng'] = { 'Geez' }, ['fre'] = { 'guèze' } } },
  ['gil'] = { iso_639_2 = { b = 'gil' }, exonym = { ['eng'] = { 'Gilbertese' }, ['fre'] = { 'kiribati' } } },
  ['gd'] = 'gla',
  ['gla'] = { iso_639_1 = 'gd', iso_639_2 = { b = 'gla' }, exonym = { ['eng'] = { 'Gaelic', 'Scottish Gaelic' }, ['fre'] = { 'gaélique', 'gaélique écossais' } } },
  ['ga'] = 'gle',
  ['gle'] = { iso_639_1 = 'ga', iso_639_2 = { b = 'gle' }, exonym = { ['eng'] = { 'Irish' }, ['fre'] = { 'irlandais' } } },
  ['gl'] = 'glg',
  ['glg'] = { iso_639_1 = 'gl', iso_639_2 = { b = 'glg' }, exonym = { ['eng'] = { 'Galician' }, ['fre'] = { 'galicien' } } },
  ['gv'] = 'glv',
  ['glv'] = { iso_639_1 = 'gv', iso_639_2 = { b = 'glv' }, exonym = { ['eng'] = { 'Manx' }, ['fre'] = { 'manx', 'mannois' } } },
  ['gmh'] = { iso_639_2 = { b = 'gmh' }, exonym = { ['eng'] = { 'German, Middle High (ca.1050-1500)' }, ['fre'] = { 'allemand, moyen haut (ca. 1050-1500)' } } },
  ['goh'] = { iso_639_2 = { b = 'goh' }, exonym = { ['eng'] = { 'German, Old High (ca.750-1050)' }, ['fre'] = { 'allemand, vieux haut (ca. 750-1050)' } } },
  ['gon'] = { iso_639_2 = { b = 'gon' }, exonym = { ['eng'] = { 'Gondi' }, ['fre'] = { 'gond' } } },
  ['gor'] = { iso_639_2 = { b = 'gor' }, exonym = { ['eng'] = { 'Gorontalo' }, ['fre'] = { 'gorontalo' } } },
  ['got'] = { iso_639_2 = { b = 'got' }, exonym = { ['eng'] = { 'Gothic' }, ['fre'] = { 'gothique' } } },
  ['grb'] = { iso_639_2 = { b = 'grb' }, exonym = { ['eng'] = { 'Grebo' }, ['fre'] = { 'grebo' } } },
  ['grc'] = { iso_639_2 = { b = 'grc' }, exonym = { ['eng'] = { 'Greek, Ancient (to 1453)' }, ['fre'] = { 'grec ancien (jusqu\'à 1453)' } } },
  ['el'] = 'gre',
  ['ell'] = 'gre',
  ['gre'] = { iso_639_1 = 'el', iso_639_2 = { b = 'gre', t = 'ell' }, exonym = { ['eng'] = { 'Modern Greek (1453-)' }, ['fre'] = { 'grec moderne (1453-)' } } },
  ['gn'] = 'grn',
  ['grn'] = { iso_639_1 = 'gn', iso_639_2 = { b = 'grn' }, exonym = { ['eng'] = { 'Guarani' }, ['fre'] = { 'guarani' } } },
  ['gsw'] = { iso_639_2 = { b = 'gsw' }, exonym = { ['eng'] = { 'Swiss German', 'Alemannic', 'Alsatian' }, ['fre'] = { 'suisse alémanique', 'alémanique', 'alsacien' } } },
  ['gu'] = 'guj',
  ['guj'] = { iso_639_1 = 'gu', iso_639_2 = { b = 'guj' }, exonym = { ['eng'] = { 'Gujarati' }, ['fre'] = { 'goudjrati' } } },
  ['gwi'] = { iso_639_2 = { b = 'gwi' }, exonym = { ['eng'] = { 'Gwich\'in' }, ['fre'] = { 'gwich\'in' } } },
  ['hai'] = { iso_639_2 = { b = 'hai' }, exonym = { ['eng'] = { 'Haida' }, ['fre'] = { 'haida' } } },
  ['ht'] = 'hat',
  ['hat'] = { iso_639_1 = 'ht', iso_639_2 = { b = 'hat' }, exonym = { ['eng'] = { 'Haitian', 'Haitian Creole' }, ['fre'] = { 'haïtien', 'créole haïtien' } } },
  ['ha'] = 'hau',
  ['hau'] = { iso_639_1 = 'ha', iso_639_2 = { b = 'hau' }, exonym = { ['eng'] = { 'Hausa' }, ['fre'] = { 'haoussa' } } },
  ['haw'] = { iso_639_2 = { b = 'haw' }, exonym = { ['eng'] = { 'Hawaiian' }, ['fre'] = { 'hawaïen' } } },
  ['he'] = 'heb',
  ['heb'] = { iso_639_1 = 'he', iso_639_2 = { b = 'heb' }, exonym = { ['eng'] = { 'Hebrew' }, ['fre'] = { 'hébreu' } } },
  ['hz'] = 'her',
  ['her'] = { iso_639_1 = 'hz', iso_639_2 = { b = 'her' }, exonym = { ['eng'] = { 'Herero' }, ['fre'] = { 'herero' } } },
  ['hil'] = { iso_639_2 = { b = 'hil' }, exonym = { ['eng'] = { 'Hiligaynon' }, ['fre'] = { 'hiligaynon' } } },
  ['him'] = { iso_639_2 = { b = 'him' }, exonym = { ['eng'] = { 'Himachali languages', 'Western Pahari languages' }, ['fre'] = { 'langues himachalis', 'langues paharis occidentales' } } },
  ['hi'] = 'hin',
  ['hin'] = { iso_639_1 = 'hi', iso_639_2 = { b = 'hin' }, exonym = { ['eng'] = { 'Hindi' }, ['fre'] = { 'hindi' } } },
  ['hit'] = { iso_639_2 = { b = 'hit' }, exonym = { ['eng'] = { 'Hittite' }, ['fre'] = { 'hittite' } } },
  ['hmn'] = { iso_639_2 = { b = 'hmn' }, exonym = { ['eng'] = { 'Hmong', 'Mong' }, ['fre'] = { 'hmong' } } },
  ['ho'] = 'hmo',
  ['hmo'] = { iso_639_1 = 'ho', iso_639_2 = { b = 'hmo' }, exonym = { ['eng'] = { 'Hiri Motu' }, ['fre'] = { 'hiri motu' } } },
  ['hr'] = 'hrv',
  ['hrv'] = { iso_639_1 = 'hr', iso_639_2 = { b = 'hrv' }, exonym = { ['eng'] = { 'Croatian' }, ['fre'] = { 'croate' } } },
  ['hsb'] = { iso_639_2 = { b = 'hsb' }, exonym = { ['eng'] = { 'Upper Sorbian' }, ['fre'] = { 'haut-sorabe' } } },
  ['hu'] = 'hun',
  ['hun'] = { iso_639_1 = 'hu', iso_639_2 = { b = 'hun' }, exonym = { ['eng'] = { 'Hungarian' }, ['fre'] = { 'hongrois' } } },
  ['hup'] = { iso_639_2 = { b = 'hup' }, exonym = { ['eng'] = { 'Hupa' }, ['fre'] = { 'hupa' } } },
  ['iba'] = { iso_639_2 = { b = 'iba' }, exonym = { ['eng'] = { 'Iban' }, ['fre'] = { 'iban' } } },
  ['ig'] = 'ibo',
  ['ibo'] = { iso_639_1 = 'ig', iso_639_2 = { b = 'ibo' }, exonym = { ['eng'] = { 'Igbo' }, ['fre'] = { 'igbo' } } },
  ['is'] = 'ice',
  ['isl'] = 'ice',
  ['ice'] = { iso_639_1 = 'is', iso_639_2 = { b = 'ice', t = 'isl' }, exonym = { ['eng'] = { 'Icelandic' }, ['fre'] = { 'islandais' } } },
  ['io'] = 'ido',
  ['ido'] = { iso_639_1 = 'io', iso_639_2 = { b = 'ido' }, exonym = { ['eng'] = { 'Ido' }, ['fre'] = { 'ido' } } },
  ['ii'] = 'iii',
  ['iii'] = { iso_639_1 = 'ii', iso_639_2 = { b = 'iii' }, exonym = { ['eng'] = { 'Sichuan Yi', 'Nuosu' }, ['fre'] = { 'yi de Sichuan' } } },
  ['ijo'] = { iso_639_2 = { b = 'ijo' }, exonym = { ['eng'] = { 'Ijo languages' }, ['fre'] = { 'ijo, langues' } } },
  ['iu'] = 'iku',
  ['iku'] = { iso_639_1 = 'iu', iso_639_2 = { b = 'iku' }, exonym = { ['eng'] = { 'Inuktitut' }, ['fre'] = { 'inuktitut' } } },
  ['ie'] = 'ile',
  ['ile'] = { iso_639_1 = 'ie', iso_639_2 = { b = 'ile' }, exonym = { ['eng'] = { 'Interlingue', 'Occidental' }, ['fre'] = { 'interlingue' } } },
  ['ilo'] = { iso_639_2 = { b = 'ilo' }, exonym = { ['eng'] = { 'Iloko' }, ['fre'] = { 'ilocano' } } },
  ['ia'] = 'ina',
  ['ina'] = { iso_639_1 = 'ia', iso_639_2 = { b = 'ina' }, exonym = { ['eng'] = { 'Interlingua (International Auxiliary Language Association)' }, ['fre'] = { 'interlingua (langue auxiliaire internationale)' } } },
  ['inc'] = { iso_639_2 = { b = 'inc' }, exonym = { ['eng'] = { 'Indic languages' }, ['fre'] = { 'indo-aryennes, langues' } } },
  ['id'] = 'ind',
  ['ind'] = { iso_639_1 = 'id', iso_639_2 = { b = 'ind' }, exonym = { ['eng'] = { 'Indonesian' }, ['fre'] = { 'indonésien' } } },
  ['ine'] = { iso_639_2 = { b = 'ine' }, exonym = { ['eng'] = { 'Indo-European languages' }, ['fre'] = { 'indo-européennes, langues' } } },
  ['inh'] = { iso_639_2 = { b = 'inh' }, exonym = { ['eng'] = { 'Ingush' }, ['fre'] = { 'ingouche' } } },
  ['ik'] = 'ipk',
  ['ipk'] = { iso_639_1 = 'ik', iso_639_2 = { b = 'ipk' }, exonym = { ['eng'] = { 'Inupiaq' }, ['fre'] = { 'inupiaq' } } },
  ['ira'] = { iso_639_2 = { b = 'ira' }, exonym = { ['eng'] = { 'Iranian languages' }, ['fre'] = { 'iraniennes, langues' } } },
  ['iro'] = { iso_639_2 = { b = 'iro' }, exonym = { ['eng'] = { 'Iroquoian languages' }, ['fre'] = { 'iroquoises, langues' } } },
  ['it'] = 'ita',
  ['ita'] = { iso_639_1 = 'it', iso_639_2 = { b = 'ita' }, exonym = { ['eng'] = { 'Italian' }, ['fre'] = { 'italien' } } },
  ['jv'] = 'jav',
  ['jav'] = { iso_639_1 = 'jv', iso_639_2 = { b = 'jav' }, exonym = { ['eng'] = { 'Javanese' }, ['fre'] = { 'javanais' } } },
  ['jbo'] = { iso_639_2 = { b = 'jbo' }, exonym = { ['eng'] = { 'Lojban' }, ['fre'] = { 'lojban' } } },
  ['ja'] = 'jpn',
  ['jpn'] = { iso_639_1 = 'ja', iso_639_2 = { b = 'jpn' }, exonym = { ['eng'] = { 'Japanese' }, ['fre'] = { 'japonais' } } },
  ['jpr'] = { iso_639_2 = { b = 'jpr' }, exonym = { ['eng'] = { 'Judeo-Persian' }, ['fre'] = { 'judéo-persan' } } },
  ['jrb'] = { iso_639_2 = { b = 'jrb' }, exonym = { ['eng'] = { 'Judeo-Arabic' }, ['fre'] = { 'judéo-arabe' } } },
  ['kaa'] = { iso_639_2 = { b = 'kaa' }, exonym = { ['eng'] = { 'Kara-Kalpak' }, ['fre'] = { 'karakalpak' } } },
  ['kab'] = { iso_639_2 = { b = 'kab' }, exonym = { ['eng'] = { 'Kabyle' }, ['fre'] = { 'kabyle' } } },
  ['kac'] = { iso_639_2 = { b = 'kac' }, exonym = { ['eng'] = { 'Kachin', 'Jingpho' }, ['fre'] = { 'kachin', 'jingpho' } } },
  ['kl'] = 'kal',
  ['kal'] = { iso_639_1 = 'kl', iso_639_2 = { b = 'kal' }, exonym = { ['eng'] = { 'Kalaallisut', 'Greenlandic' }, ['fre'] = { 'groenlandais' } } },
  ['kam'] = { iso_639_2 = { b = 'kam' }, exonym = { ['eng'] = { 'Kamba' }, ['fre'] = { 'kamba' } } },
  ['kn'] = 'kan',
  ['kan'] = { iso_639_1 = 'kn', iso_639_2 = { b = 'kan' }, exonym = { ['eng'] = { 'Kannada' }, ['fre'] = { 'kannada' } } },
  ['kar'] = { iso_639_2 = { b = 'kar' }, exonym = { ['eng'] = { 'Karen languages' }, ['fre'] = { 'karen, langues' } } },
  ['ks'] = 'kas',
  ['kas'] = { iso_639_1 = 'ks', iso_639_2 = { b = 'kas' }, exonym = { ['eng'] = { 'Kashmiri' }, ['fre'] = { 'kashmiri' } } },
  ['kr'] = 'kau',
  ['kau'] = { iso_639_1 = 'kr', iso_639_2 = { b = 'kau' }, exonym = { ['eng'] = { 'Kanuri' }, ['fre'] = { 'kanouri' } } },
  ['kaw'] = { iso_639_2 = { b = 'kaw' }, exonym = { ['eng'] = { 'Kawi' }, ['fre'] = { 'kawi' } } },
  ['kk'] = 'kaz',
  ['kaz'] = { iso_639_1 = 'kk', iso_639_2 = { b = 'kaz' }, exonym = { ['eng'] = { 'Kazakh' }, ['fre'] = { 'kazakh' } } },
  ['kbd'] = { iso_639_2 = { b = 'kbd' }, exonym = { ['eng'] = { 'Kabardian' }, ['fre'] = { 'kabardien' } } },
  ['kha'] = { iso_639_2 = { b = 'kha' }, exonym = { ['eng'] = { 'Khasi' }, ['fre'] = { 'khasi' } } },
  ['khi'] = { iso_639_2 = { b = 'khi' }, exonym = { ['eng'] = { 'Khoisan languages' }, ['fre'] = { 'khoïsan, langues' } } },
  ['km'] = 'khm',
  ['khm'] = { iso_639_1 = 'km', iso_639_2 = { b = 'khm' }, exonym = { ['eng'] = { 'Central Khmer' }, ['fre'] = { 'khmer central' } } },
  ['kho'] = { iso_639_2 = { b = 'kho' }, exonym = { ['eng'] = { 'Khotanese', 'Sakan' }, ['fre'] = { 'khotanais', 'sakan' } } },
  ['ki'] = 'kik',
  ['kik'] = { iso_639_1 = 'ki', iso_639_2 = { b = 'kik' }, exonym = { ['eng'] = { 'Kikuyu', 'Gikuyu' }, ['fre'] = { 'kikuyu' } } },
  ['rw'] = 'kin',
  ['kin'] = { iso_639_1 = 'rw', iso_639_2 = { b = 'kin' }, exonym = { ['eng'] = { 'Kinyarwanda' }, ['fre'] = { 'rwanda' } } },
  ['ky'] = 'kir',
  ['kir'] = { iso_639_1 = 'ky', iso_639_2 = { b = 'kir' }, exonym = { ['eng'] = { 'Kirghiz', 'Kyrgyz' }, ['fre'] = { 'kirghiz' } } },
  ['kmb'] = { iso_639_2 = { b = 'kmb' }, exonym = { ['eng'] = { 'Kimbundu' }, ['fre'] = { 'kimbundu' } } },
  ['kok'] = { iso_639_2 = { b = 'kok' }, exonym = { ['eng'] = { 'Konkani' }, ['fre'] = { 'konkani' } } },
  ['kv'] = 'kom',
  ['kom'] = { iso_639_1 = 'kv', iso_639_2 = { b = 'kom' }, exonym = { ['eng'] = { 'Komi' }, ['fre'] = { 'kom' } } },
  ['kg'] = 'kon',
  ['kon'] = { iso_639_1 = 'kg', iso_639_2 = { b = 'kon' }, exonym = { ['eng'] = { 'Kongo' }, ['fre'] = { 'kongo' } } },
  ['ko'] = 'kor',
  ['kor'] = { iso_639_1 = 'ko', iso_639_2 = { b = 'kor' }, exonym = { ['eng'] = { 'Korean' }, ['fre'] = { 'coréen' } } },
  ['kos'] = { iso_639_2 = { b = 'kos' }, exonym = { ['eng'] = { 'Kosraean' }, ['fre'] = { 'kosrae' } } },
  ['kpe'] = { iso_639_2 = { b = 'kpe' }, exonym = { ['eng'] = { 'Kpelle' }, ['fre'] = { 'kpellé' } } },
  ['krc'] = { iso_639_2 = { b = 'krc' }, exonym = { ['eng'] = { 'Karachay-Balkar' }, ['fre'] = { 'karatchai balkar' } } },
  ['krl'] = { iso_639_2 = { b = 'krl' }, exonym = { ['eng'] = { 'Karelian' }, ['fre'] = { 'carélien' } } },
  ['kro'] = { iso_639_2 = { b = 'kro' }, exonym = { ['eng'] = { 'Kru languages' }, ['fre'] = { 'krou, langues' } } },
  ['kru'] = { iso_639_2 = { b = 'kru' }, exonym = { ['eng'] = { 'Kurukh' }, ['fre'] = { 'kurukh' } } },
  ['kj'] = 'kua',
  ['kua'] = { iso_639_1 = 'kj', iso_639_2 = { b = 'kua' }, exonym = { ['eng'] = { 'Kuanyama', 'Kwanyama' }, ['fre'] = { 'kuanyama', 'kwanyama' } } },
  ['kum'] = { iso_639_2 = { b = 'kum' }, exonym = { ['eng'] = { 'Kumyk' }, ['fre'] = { 'koumyk' } } },
  ['ku'] = 'kur',
  ['kur'] = { iso_639_1 = 'ku', iso_639_2 = { b = 'kur' }, exonym = { ['eng'] = { 'Kurdish' }, ['fre'] = { 'kurde' } } },
  ['kut'] = { iso_639_2 = { b = 'kut' }, exonym = { ['eng'] = { 'Kutenai' }, ['fre'] = { 'kutenai' } } },
  ['lad'] = { iso_639_2 = { b = 'lad' }, exonym = { ['eng'] = { 'Ladino' }, ['fre'] = { 'judéo-espagnol' } } },
  ['lah'] = { iso_639_2 = { b = 'lah' }, exonym = { ['eng'] = { 'Lahnda' }, ['fre'] = { 'lahnda' } } },
  ['lam'] = { iso_639_2 = { b = 'lam' }, exonym = { ['eng'] = { 'Lamba' }, ['fre'] = { 'lamba' } } },
  ['lo'] = 'lao',
  ['lao'] = { iso_639_1 = 'lo', iso_639_2 = { b = 'lao' }, exonym = { ['eng'] = { 'Lao' }, ['fre'] = { 'lao' } } },
  ['la'] = 'lat',
  ['lat'] = { iso_639_1 = 'la', iso_639_2 = { b = 'lat' }, exonym = { ['eng'] = { 'Latin' }, ['fre'] = { 'latin' } } },
  ['lv'] = 'lav',
  ['lav'] = { iso_639_1 = 'lv', iso_639_2 = { b = 'lav' }, exonym = { ['eng'] = { 'Latvian' }, ['fre'] = { 'letton' } } },
  ['lez'] = { iso_639_2 = { b = 'lez' }, exonym = { ['eng'] = { 'Lezghian' }, ['fre'] = { 'lezghien' } } },
  ['li'] = 'lim',
  ['lim'] = { iso_639_1 = 'li', iso_639_2 = { b = 'lim' }, exonym = { ['eng'] = { 'Limburgan', 'Limburger', 'Limburgish' }, ['fre'] = { 'limbourgeois' } } },
  ['ln'] = 'lin',
  ['lin'] = { iso_639_1 = 'ln', iso_639_2 = { b = 'lin' }, exonym = { ['eng'] = { 'Lingala' }, ['fre'] = { 'lingala' } } },
  ['lt'] = 'lit',
  ['lit'] = { iso_639_1 = 'lt', iso_639_2 = { b = 'lit' }, exonym = { ['eng'] = { 'Lithuanian' }, ['fre'] = { 'lituanien' } } },
  ['lol'] = { iso_639_2 = { b = 'lol' }, exonym = { ['eng'] = { 'Mongo' }, ['fre'] = { 'mongo' } } },
  ['loz'] = { iso_639_2 = { b = 'loz' }, exonym = { ['eng'] = { 'Lozi' }, ['fre'] = { 'lozi' } } },
  ['lb'] = 'ltz',
  ['ltz'] = { iso_639_1 = 'lb', iso_639_2 = { b = 'ltz' }, exonym = { ['eng'] = { 'Luxembourgish', 'Letzeburgesch' }, ['fre'] = { 'luxembourgeois' } } },
  ['lua'] = { iso_639_2 = { b = 'lua' }, exonym = { ['eng'] = { 'Luba-Lulua' }, ['fre'] = { 'luba-lulua' } } },
  ['lu'] = 'lub',
  ['lub'] = { iso_639_1 = 'lu', iso_639_2 = { b = 'lub' }, exonym = { ['eng'] = { 'Luba-Katanga' }, ['fre'] = { 'luba-katanga' } } },
  ['lg'] = 'lug',
  ['lug'] = { iso_639_1 = 'lg', iso_639_2 = { b = 'lug' }, exonym = { ['eng'] = { 'Ganda' }, ['fre'] = { 'ganda' } } },
  ['lui'] = { iso_639_2 = { b = 'lui' }, exonym = { ['eng'] = { 'Luiseno' }, ['fre'] = { 'luiseno' } } },
  ['lun'] = { iso_639_2 = { b = 'lun' }, exonym = { ['eng'] = { 'Lunda' }, ['fre'] = { 'lunda' } } },
  ['luo'] = { iso_639_2 = { b = 'luo' }, exonym = { ['eng'] = { 'Luo (Kenya and Tanzania)' }, ['fre'] = { 'luo (Kenya et Tanzanie)' } } },
  ['lus'] = { iso_639_2 = { b = 'lus' }, exonym = { ['eng'] = { 'Lushai' }, ['fre'] = { 'lushai' } } },
  ['mk'] = 'mac',
  ['mkd'] = 'mac',
  ['mac'] = { iso_639_1 = 'mk', iso_639_2 = { b = 'mac', t = 'mkd' }, exonym = { ['eng'] = { 'Macedonian' }, ['fre'] = { 'macédonien' } } },
  ['mad'] = { iso_639_2 = { b = 'mad' }, exonym = { ['eng'] = { 'Madurese' }, ['fre'] = { 'madourais' } } },
  ['mag'] = { iso_639_2 = { b = 'mag' }, exonym = { ['eng'] = { 'Magahi' }, ['fre'] = { 'magahi' } } },
  ['mh'] = 'mah',
  ['mah'] = { iso_639_1 = 'mh', iso_639_2 = { b = 'mah' }, exonym = { ['eng'] = { 'Marshallese' }, ['fre'] = { 'marshall' } } },
  ['mai'] = { iso_639_2 = { b = 'mai' }, exonym = { ['eng'] = { 'Maithili' }, ['fre'] = { 'maithili' } } },
  ['mak'] = { iso_639_2 = { b = 'mak' }, exonym = { ['eng'] = { 'Makasar' }, ['fre'] = { 'makassar' } } },
  ['ml'] = 'mal',
  ['mal'] = { iso_639_1 = 'ml', iso_639_2 = { b = 'mal' }, exonym = { ['eng'] = { 'Malayalam' }, ['fre'] = { 'malayalam' } } },
  ['man'] = { iso_639_2 = { b = 'man' }, exonym = { ['eng'] = { 'Mandingo' }, ['fre'] = { 'mandingue' } } },
  ['mi'] = 'mao',
  ['mri'] = 'mao',
  ['mao'] = { iso_639_1 = 'mi', iso_639_2 = { b = 'mao', t = 'mri' }, exonym = { ['eng'] = { 'Maori' }, ['fre'] = { 'maori' } } },
  ['map'] = { iso_639_2 = { b = 'map' }, exonym = { ['eng'] = { 'Austronesian languages' }, ['fre'] = { 'austronésiennes, langues' } } },
  ['mr'] = 'mar',
  ['mar'] = { iso_639_1 = 'mr', iso_639_2 = { b = 'mar' }, exonym = { ['eng'] = { 'Marathi' }, ['fre'] = { 'marathe' } } },
  ['mas'] = { iso_639_2 = { b = 'mas' }, exonym = { ['eng'] = { 'Masai' }, ['fre'] = { 'massaï' } } },
  ['ms'] = 'may',
  ['msa'] = 'may',
  ['may'] = { iso_639_1 = 'ms', iso_639_2 = { b = 'may', t = 'msa' }, exonym = { ['eng'] = { 'Malay' }, ['fre'] = { 'malais' } } },
  ['mdf'] = { iso_639_2 = { b = 'mdf' }, exonym = { ['eng'] = { 'Moksha' }, ['fre'] = { 'moksa' } } },
  ['mdr'] = { iso_639_2 = { b = 'mdr' }, exonym = { ['eng'] = { 'Mandar' }, ['fre'] = { 'mandar' } } },
  ['men'] = { iso_639_2 = { b = 'men' }, exonym = { ['eng'] = { 'Mende' }, ['fre'] = { 'mendé' } } },
  ['mga'] = { iso_639_2 = { b = 'mga' }, exonym = { ['eng'] = { 'Irish, Middle (900-1200)' }, ['fre'] = { 'irlandais moyen (900-1200)' } } },
  ['mic'] = { iso_639_2 = { b = 'mic' }, exonym = { ['eng'] = { 'Mi\'kmaq', 'Micmac' }, ['fre'] = { 'mi\'kmaq', 'micmac' } } },
  ['min'] = { iso_639_2 = { b = 'min' }, exonym = { ['eng'] = { 'Minangkabau' }, ['fre'] = { 'minangkabau' } } },
  ['mis'] = { iso_639_2 = { b = 'mis' }, exonym = { ['eng'] = { 'Uncoded languages' }, ['fre'] = { 'langues non codées' } } },
  ['mkh'] = { iso_639_2 = { b = 'mkh' }, exonym = { ['eng'] = { 'Mon-Khmer languages' }, ['fre'] = { 'môn-khmer, langues' } } },
  ['mg'] = 'mlg',
  ['mlg'] = { iso_639_1 = 'mg', iso_639_2 = { b = 'mlg' }, exonym = { ['eng'] = { 'Malagasy' }, ['fre'] = { 'malgache' } } },
  ['mt'] = 'mlt',
  ['mlt'] = { iso_639_1 = 'mt', iso_639_2 = { b = 'mlt' }, exonym = { ['eng'] = { 'Maltese' }, ['fre'] = { 'maltais' } } },
  ['mnc'] = { iso_639_2 = { b = 'mnc' }, exonym = { ['eng'] = { 'Manchu' }, ['fre'] = { 'mandchou' } } },
  ['mni'] = { iso_639_2 = { b = 'mni' }, exonym = { ['eng'] = { 'Manipuri' }, ['fre'] = { 'manipuri' } } },
  ['mno'] = { iso_639_2 = { b = 'mno' }, exonym = { ['eng'] = { 'Manobo languages' }, ['fre'] = { 'manobo, langues' } } },
  ['moh'] = { iso_639_2 = { b = 'moh' }, exonym = { ['eng'] = { 'Mohawk' }, ['fre'] = { 'mohawk' } } },
  ['mn'] = 'mon',
  ['mon'] = { iso_639_1 = 'mn', iso_639_2 = { b = 'mon' }, exonym = { ['eng'] = { 'Mongolian' }, ['fre'] = { 'mongol' } } },
  ['mos'] = { iso_639_2 = { b = 'mos' }, exonym = { ['eng'] = { 'Mossi' }, ['fre'] = { 'moré' } } },
  ['mul'] = { iso_639_2 = { b = 'mul' }, exonym = { ['eng'] = { 'Multiple languages' }, ['fre'] = { 'multilingue' } } },
  ['mun'] = { iso_639_2 = { b = 'mun' }, exonym = { ['eng'] = { 'Munda languages' }, ['fre'] = { 'mounda, langues' } } },
  ['mus'] = { iso_639_2 = { b = 'mus' }, exonym = { ['eng'] = { 'Creek' }, ['fre'] = { 'muskogee' } } },
  ['mwl'] = { iso_639_2 = { b = 'mwl' }, exonym = { ['eng'] = { 'Mirandese' }, ['fre'] = { 'mirandais' } } },
  ['mwr'] = { iso_639_2 = { b = 'mwr' }, exonym = { ['eng'] = { 'Marwari' }, ['fre'] = { 'marvari' } } },
  ['myn'] = { iso_639_2 = { b = 'myn' }, exonym = { ['eng'] = { 'Mayan languages' }, ['fre'] = { 'maya, langues' } } },
  ['myv'] = { iso_639_2 = { b = 'myv' }, exonym = { ['eng'] = { 'Erzya' }, ['fre'] = { 'erza' } } },
  ['nah'] = { iso_639_2 = { b = 'nah' }, exonym = { ['eng'] = { 'Nahuatl languages' }, ['fre'] = { 'nahuatl, langues' } } },
  ['nai'] = { iso_639_2 = { b = 'nai' }, exonym = { ['eng'] = { 'North American Indian languages' }, ['fre'] = { 'nord-amérindiennes, langues' } } },
  ['nap'] = { iso_639_2 = { b = 'nap' }, exonym = { ['eng'] = { 'Neapolitan' }, ['fre'] = { 'napolitain' } } },
  ['na'] = 'nau',
  ['nau'] = { iso_639_1 = 'na', iso_639_2 = { b = 'nau' }, exonym = { ['eng'] = { 'Nauru' }, ['fre'] = { 'nauruan' } } },
  ['nv'] = 'nav',
  ['nav'] = { iso_639_1 = 'nv', iso_639_2 = { b = 'nav' }, exonym = { ['eng'] = { 'Navajo', 'Navaho' }, ['fre'] = { 'navaho' } } },
  ['nr'] = 'nbl',
  ['nbl'] = { iso_639_1 = 'nr', iso_639_2 = { b = 'nbl' }, exonym = { ['eng'] = { 'South Ndebele' }, ['fre'] = { 'ndébélé du Sud' } } },
  ['nd'] = 'nde',
  ['nde'] = { iso_639_1 = 'nd', iso_639_2 = { b = 'nde' }, exonym = { ['eng'] = { 'North Ndebele' }, ['fre'] = { 'ndébélé du Nord' } } },
  ['ng'] = 'ndo',
  ['ndo'] = { iso_639_1 = 'ng', iso_639_2 = { b = 'ndo' }, exonym = { ['eng'] = { 'Ndonga' }, ['fre'] = { 'ndonga' } } },
  ['nds'] = { iso_639_2 = { b = 'nds' }, exonym = { ['eng'] = { 'Low German', 'Low Saxon', 'German, Low', 'Saxon, Low' }, ['fre'] = { 'bas allemand', 'bas saxon', 'allemand, bas', 'saxon, bas' } } },
  ['ne'] = 'nep',
  ['nep'] = { iso_639_1 = 'ne', iso_639_2 = { b = 'nep' }, exonym = { ['eng'] = { 'Nepali' }, ['fre'] = { 'népalais' } } },
  ['new'] = { iso_639_2 = { b = 'new' }, exonym = { ['eng'] = { 'Nepal Bhasa', 'Newar', 'Newari' }, ['fre'] = { 'nepal bhasa', 'néwar', 'newari' } } },
  ['nia'] = { iso_639_2 = { b = 'nia' }, exonym = { ['eng'] = { 'Nias' }, ['fre'] = { 'nias' } } },
  ['nic'] = { iso_639_2 = { b = 'nic' }, exonym = { ['eng'] = { 'Niger-Kordofanian languages' }, ['fre'] = { 'nigéro-kordofaniennes, langues' } } },
  ['niu'] = { iso_639_2 = { b = 'niu' }, exonym = { ['eng'] = { 'Niuean' }, ['fre'] = { 'niué' } } },
  ['nn'] = 'nno',
  ['nno'] = { iso_639_1 = 'nn', iso_639_2 = { b = 'nno' }, exonym = { ['eng'] = { 'Norwegian Nynorsk' }, ['fre'] = { 'norvégien nynorsk' } } },
  ['nb'] = 'nob',
  ['nob'] = { iso_639_1 = 'nb', iso_639_2 = { b = 'nob' }, exonym = { ['eng'] = { 'Norwegian Bokmål' }, ['fre'] = { 'norvégien bokmål' } } },
  ['nog'] = { iso_639_2 = { b = 'nog' }, exonym = { ['eng'] = { 'Nogai' }, ['fre'] = { 'nogaï', 'nogay' } } },
  ['non'] = { iso_639_2 = { b = 'non' }, exonym = { ['eng'] = { 'Norse, Old' }, ['fre'] = { 'norrois, vieux' } } },
  ['no'] = 'nor',
  ['nor'] = { iso_639_1 = 'no', iso_639_2 = { b = 'nor' }, exonym = { ['eng'] = { 'Norwegian' }, ['fre'] = { 'norvégien' } } },
  ['nqo'] = { iso_639_2 = { b = 'nqo' }, exonym = { ['eng'] = { 'N\'Ko' }, ['fre'] = { 'n\'ko' } } },
  ['nso'] = { iso_639_2 = { b = 'nso' }, exonym = { ['eng'] = { 'Pedi', 'Sepedi', 'Northern Sotho' }, ['fre'] = { 'pedi', 'sepedi', 'sotho du Nord' } } },
  ['nub'] = { iso_639_2 = { b = 'nub' }, exonym = { ['eng'] = { 'Nubian languages' }, ['fre'] = { 'nubiennes, langues' } } },
  ['nwc'] = { iso_639_2 = { b = 'nwc' }, exonym = { ['eng'] = { 'Classical Newari', 'Old Newari', 'Classical Nepal Bhasa' }, ['fre'] = { 'newari classique' } } },
  ['ny'] = 'nya',
  ['nya'] = { iso_639_1 = 'ny', iso_639_2 = { b = 'nya' }, exonym = { ['eng'] = { 'Chichewa', 'Chewa', 'Nyanja' }, ['fre'] = { 'chichewa', 'chewa', 'nyanja' } } },
  ['nym'] = { iso_639_2 = { b = 'nym' }, exonym = { ['eng'] = { 'Nyamwezi' }, ['fre'] = { 'nyamwezi' } } },
  ['nyn'] = { iso_639_2 = { b = 'nyn' }, exonym = { ['eng'] = { 'Nyankole' }, ['fre'] = { 'nyankolé' } } },
  ['nyo'] = { iso_639_2 = { b = 'nyo' }, exonym = { ['eng'] = { 'Nyoro' }, ['fre'] = { 'nyoro' } } },
  ['nzi'] = { iso_639_2 = { b = 'nzi' }, exonym = { ['eng'] = { 'Nzima' }, ['fre'] = { 'nzema' } } },
  ['oc'] = 'oci',
  ['oci'] = { iso_639_1 = 'oc', iso_639_2 = { b = 'oci' }, exonym = { ['eng'] = { 'Occitan (post 1500)' }, ['fre'] = { 'occitan (après 1500)' } } },
  ['oj'] = 'oji',
  ['oji'] = { iso_639_1 = 'oj', iso_639_2 = { b = 'oji' }, exonym = { ['eng'] = { 'Ojibwa' }, ['fre'] = { 'ojibwa' } } },
  ['or'] = 'ori',
  ['ori'] = { iso_639_1 = 'or', iso_639_2 = { b = 'ori' }, exonym = { ['eng'] = { 'Oriya' }, ['fre'] = { 'oriya' } } },
  ['om'] = 'orm',
  ['orm'] = { iso_639_1 = 'om', iso_639_2 = { b = 'orm' }, exonym = { ['eng'] = { 'Oromo' }, ['fre'] = { 'galla' } } },
  ['osa'] = { iso_639_2 = { b = 'osa' }, exonym = { ['eng'] = { 'Osage' }, ['fre'] = { 'osage' } } },
  ['os'] = 'oss',
  ['oss'] = { iso_639_1 = 'os', iso_639_2 = { b = 'oss' }, exonym = { ['eng'] = { 'Ossetian', 'Ossetic' }, ['fre'] = { 'ossète' } } },
  ['ota'] = { iso_639_2 = { b = 'ota' }, exonym = { ['eng'] = { 'Turkish, Ottoman (1500-1928)' }, ['fre'] = { 'turc ottoman (1500-1928)' } } },
  ['oto'] = { iso_639_2 = { b = 'oto' }, exonym = { ['eng'] = { 'Otomian languages' }, ['fre'] = { 'otomi, langues' } } },
  ['paa'] = { iso_639_2 = { b = 'paa' }, exonym = { ['eng'] = { 'Papuan languages' }, ['fre'] = { 'papoues, langues' } } },
  ['pag'] = { iso_639_2 = { b = 'pag' }, exonym = { ['eng'] = { 'Pangasinan' }, ['fre'] = { 'pangasinan' } } },
  ['pal'] = { iso_639_2 = { b = 'pal' }, exonym = { ['eng'] = { 'Pahlavi' }, ['fre'] = { 'pahlavi' } } },
  ['pam'] = { iso_639_2 = { b = 'pam' }, exonym = { ['eng'] = { 'Pampanga', 'Kapampangan' }, ['fre'] = { 'pampangan' } } },
  ['pa'] = 'pan',
  ['pan'] = { iso_639_1 = 'pa', iso_639_2 = { b = 'pan' }, exonym = { ['eng'] = { 'Panjabi', 'Punjabi' }, ['fre'] = { 'pendjabi' } } },
  ['pap'] = { iso_639_2 = { b = 'pap' }, exonym = { ['eng'] = { 'Papiamento' }, ['fre'] = { 'papiamento' } } },
  ['pau'] = { iso_639_2 = { b = 'pau' }, exonym = { ['eng'] = { 'Palauan' }, ['fre'] = { 'palau' } } },
  ['peo'] = { iso_639_2 = { b = 'peo' }, exonym = { ['eng'] = { 'Persian, Old (ca.600-400 B.C.)' }, ['fre'] = { 'perse, vieux (ca. 600-400 av. J.-C.)' } } },
  ['fa'] = 'per',
  ['fas'] = 'per',
  ['per'] = { iso_639_1 = 'fa', iso_639_2 = { b = 'per', t = 'fas' }, exonym = { ['eng'] = { 'Persian' }, ['fre'] = { 'persan' } } },
  ['phi'] = { iso_639_2 = { b = 'phi' }, exonym = { ['eng'] = { 'Philippine languages' }, ['fre'] = { 'philippines, langues' } } },
  ['phn'] = { iso_639_2 = { b = 'phn' }, exonym = { ['eng'] = { 'Phoenician' }, ['fre'] = { 'phénicien' } } },
  ['pi'] = 'pli',
  ['pli'] = { iso_639_1 = 'pi', iso_639_2 = { b = 'pli' }, exonym = { ['eng'] = { 'Pali' }, ['fre'] = { 'pali' } } },
  ['pl'] = 'pol',
  ['pol'] = { iso_639_1 = 'pl', iso_639_2 = { b = 'pol' }, exonym = { ['eng'] = { 'Polish' }, ['fre'] = { 'polonais' } } },
  ['pon'] = { iso_639_2 = { b = 'pon' }, exonym = { ['eng'] = { 'Pohnpeian' }, ['fre'] = { 'pohnpei' } } },
  ['pt'] = 'por',
  ['por'] = { iso_639_1 = 'pt', iso_639_2 = { b = 'por' }, exonym = { ['eng'] = { 'Portuguese' }, ['fre'] = { 'portugais' } } },
  ['pra'] = { iso_639_2 = { b = 'pra' }, exonym = { ['eng'] = { 'Prakrit languages' }, ['fre'] = { 'prâkrit, langues' } } },
  ['pro'] = { iso_639_2 = { b = 'pro' }, exonym = { ['eng'] = { 'Provençal, Old (to 1500)', 'Occitan, Old (to 1500)' }, ['fre'] = { 'provençal ancien (jusqu\'à 1500)', 'occitan ancien (jusqu\'à 1500)' } } },
  ['ps'] = 'pus',
  ['pus'] = { iso_639_1 = 'ps', iso_639_2 = { b = 'pus' }, exonym = { ['eng'] = { 'Pushto', 'Pashto' }, ['fre'] = { 'pachto' } } },
  ['qaa-qtz'] = { iso_639_2 = { b = 'qaa-qtz' }, exonym = { ['eng'] = { 'Reserved for local use' }, ['fre'] = { 'réservée à l\'usage local' } } },
  ['qu'] = 'que',
  ['que'] = { iso_639_1 = 'qu', iso_639_2 = { b = 'que' }, exonym = { ['eng'] = { 'Quechua' }, ['fre'] = { 'quechua' } } },
  ['raj'] = { iso_639_2 = { b = 'raj' }, exonym = { ['eng'] = { 'Rajasthani' }, ['fre'] = { 'rajasthani' } } },
  ['rap'] = { iso_639_2 = { b = 'rap' }, exonym = { ['eng'] = { 'Rapanui' }, ['fre'] = { 'rapanui' } } },
  ['rar'] = { iso_639_2 = { b = 'rar' }, exonym = { ['eng'] = { 'Rarotongan', 'Cook Islands Maori' }, ['fre'] = { 'rarotonga', 'maori des îles Cook' } } },
  ['roa'] = { iso_639_2 = { b = 'roa' }, exonym = { ['eng'] = { 'Romance languages' }, ['fre'] = { 'romanes, langues' } } },
  ['rm'] = 'roh',
  ['roh'] = { iso_639_1 = 'rm', iso_639_2 = { b = 'roh' }, exonym = { ['eng'] = { 'Romansh' }, ['fre'] = { 'romanche' } } },
  ['rom'] = { iso_639_2 = { b = 'rom' }, exonym = { ['eng'] = { 'Romany' }, ['fre'] = { 'tsigane' } } },
  ['ro'] = 'rum',
  ['ron'] = 'rum',
  ['rum'] = { iso_639_1 = 'ro', iso_639_2 = { b = 'rum', t = 'ron' }, exonym = { ['eng'] = { 'Romanian', 'Moldavian', 'Moldovan' }, ['fre'] = { 'roumain', 'moldave' } } },
  ['rn'] = 'run',
  ['run'] = { iso_639_1 = 'rn', iso_639_2 = { b = 'run' }, exonym = { ['eng'] = { 'Rundi' }, ['fre'] = { 'rundi' } } },
  ['rup'] = { iso_639_2 = { b = 'rup' }, exonym = { ['eng'] = { 'Aromanian', 'Arumanian', 'Macedo-Romanian' }, ['fre'] = { 'aroumain', 'macédo-roumain' } } },
  ['ru'] = 'rus',
  ['rus'] = { iso_639_1 = 'ru', iso_639_2 = { b = 'rus' }, exonym = { ['eng'] = { 'Russian' }, ['fre'] = { 'russe' } } },
  ['sad'] = { iso_639_2 = { b = 'sad' }, exonym = { ['eng'] = { 'Sandawe' }, ['fre'] = { 'sandawe' } } },
  ['sg'] = 'sag',
  ['sag'] = { iso_639_1 = 'sg', iso_639_2 = { b = 'sag' }, exonym = { ['eng'] = { 'Sango' }, ['fre'] = { 'sango' } } },
  ['sah'] = { iso_639_2 = { b = 'sah' }, exonym = { ['eng'] = { 'Yakut' }, ['fre'] = { 'iakoute' } } },
  ['sai'] = { iso_639_2 = { b = 'sai' }, exonym = { ['eng'] = { 'South American Indian languages' }, ['fre'] = { 'sud-amérindiennes, langues' } } },
  ['sal'] = { iso_639_2 = { b = 'sal' }, exonym = { ['eng'] = { 'Salishan languages' }, ['fre'] = { 'salishennes, langues' } } },
  ['sam'] = { iso_639_2 = { b = 'sam' }, exonym = { ['eng'] = { 'Samaritan Aramaic' }, ['fre'] = { 'samaritain' } } },
  ['sa'] = 'san',
  ['san'] = { iso_639_1 = 'sa', iso_639_2 = { b = 'san' }, exonym = { ['eng'] = { 'Sanskrit' }, ['fre'] = { 'sanskrit' } } },
  ['sas'] = { iso_639_2 = { b = 'sas' }, exonym = { ['eng'] = { 'Sasak' }, ['fre'] = { 'sasak' } } },
  ['sat'] = { iso_639_2 = { b = 'sat' }, exonym = { ['eng'] = { 'Santali' }, ['fre'] = { 'santal' } } },
  ['scn'] = { iso_639_2 = { b = 'scn' }, exonym = { ['eng'] = { 'Sicilian' }, ['fre'] = { 'sicilien' } } },
  ['sco'] = { iso_639_2 = { b = 'sco' }, exonym = { ['eng'] = { 'Scots' }, ['fre'] = { 'écossais' } } },
  ['sel'] = { iso_639_2 = { b = 'sel' }, exonym = { ['eng'] = { 'Selkup' }, ['fre'] = { 'selkoupe' } } },
  ['sem'] = { iso_639_2 = { b = 'sem' }, exonym = { ['eng'] = { 'Semitic languages' }, ['fre'] = { 'sémitiques, langues' } } },
  ['sga'] = { iso_639_2 = { b = 'sga' }, exonym = { ['eng'] = { 'Irish, Old (to 900)' }, ['fre'] = { 'irlandais ancien (jusqu\'à 900)' } } },
  ['sgn'] = { iso_639_2 = { b = 'sgn' }, exonym = { ['eng'] = { 'Sign Languages' }, ['fre'] = { 'langues des signes' } } },
  ['shn'] = { iso_639_2 = { b = 'shn' }, exonym = { ['eng'] = { 'Shan' }, ['fre'] = { 'chan' } } },
  ['sid'] = { iso_639_2 = { b = 'sid' }, exonym = { ['eng'] = { 'Sidamo' }, ['fre'] = { 'sidamo' } } },
  ['si'] = 'sin',
  ['sin'] = { iso_639_1 = 'si', iso_639_2 = { b = 'sin' }, exonym = { ['eng'] = { 'Sinhala', 'Sinhalese' }, ['fre'] = { 'singhalais' } } },
  ['sio'] = { iso_639_2 = { b = 'sio' }, exonym = { ['eng'] = { 'Siouan languages' }, ['fre'] = { 'sioux, langues' } } },
  ['sit'] = { iso_639_2 = { b = 'sit' }, exonym = { ['eng'] = { 'Sino-Tibetan languages' }, ['fre'] = { 'sino-tibétaines, langues' } } },
  ['sla'] = { iso_639_2 = { b = 'sla' }, exonym = { ['eng'] = { 'Slavic languages' }, ['fre'] = { 'slaves, langues' } } },
  ['sk'] = 'slo',
  ['slk'] = 'slo',
  ['slo'] = { iso_639_1 = 'sk', iso_639_2 = { b = 'slo', t = 'slk' }, exonym = { ['eng'] = { 'Slovak' }, ['fre'] = { 'slovaque' } } },
  ['sl'] = 'slv',
  ['slv'] = { iso_639_1 = 'sl', iso_639_2 = { b = 'slv' }, exonym = { ['eng'] = { 'Slovenian' }, ['fre'] = { 'slovène' } } },
  ['sma'] = { iso_639_2 = { b = 'sma' }, exonym = { ['eng'] = { 'Southern Sami' }, ['fre'] = { 'sami du Sud' } } },
  ['se'] = 'sme',
  ['sme'] = { iso_639_1 = 'se', iso_639_2 = { b = 'sme' }, exonym = { ['eng'] = { 'Northern Sami' }, ['fre'] = { 'sami du Nord' } } },
  ['smi'] = { iso_639_2 = { b = 'smi' }, exonym = { ['eng'] = { 'Sami languages' }, ['fre'] = { 'sames, langues' } } },
  ['smj'] = { iso_639_2 = { b = 'smj' }, exonym = { ['eng'] = { 'Lule Sami' }, ['fre'] = { 'sami de Lule' } } },
  ['smn'] = { iso_639_2 = { b = 'smn' }, exonym = { ['eng'] = { 'Inari Sami' }, ['fre'] = { 'sami d\'Inari' } } },
  ['sm'] = 'smo',
  ['smo'] = { iso_639_1 = 'sm', iso_639_2 = { b = 'smo' }, exonym = { ['eng'] = { 'Samoan' }, ['fre'] = { 'samoan' } } },
  ['sms'] = { iso_639_2 = { b = 'sms' }, exonym = { ['eng'] = { 'Skolt Sami' }, ['fre'] = { 'sami skolt' } } },
  ['sn'] = 'sna',
  ['sna'] = { iso_639_1 = 'sn', iso_639_2 = { b = 'sna' }, exonym = { ['eng'] = { 'Shona' }, ['fre'] = { 'shona' } } },
  ['sd'] = 'snd',
  ['snd'] = { iso_639_1 = 'sd', iso_639_2 = { b = 'snd' }, exonym = { ['eng'] = { 'Sindhi' }, ['fre'] = { 'sindhi' } } },
  ['snk'] = { iso_639_2 = { b = 'snk' }, exonym = { ['eng'] = { 'Soninke' }, ['fre'] = { 'soninké' } } },
  ['sog'] = { iso_639_2 = { b = 'sog' }, exonym = { ['eng'] = { 'Sogdian' }, ['fre'] = { 'sogdien' } } },
  ['so'] = 'som',
  ['som'] = { iso_639_1 = 'so', iso_639_2 = { b = 'som' }, exonym = { ['eng'] = { 'Somali' }, ['fre'] = { 'somali' } } },
  ['son'] = { iso_639_2 = { b = 'son' }, exonym = { ['eng'] = { 'Songhai languages' }, ['fre'] = { 'songhai, langues' } } },
  ['st'] = 'sot',
  ['sot'] = { iso_639_1 = 'st', iso_639_2 = { b = 'sot' }, exonym = { ['eng'] = { 'Sotho, Southern' }, ['fre'] = { 'sotho du Sud' } } },
  ['es'] = 'spa',
  ['spa'] = { iso_639_1 = 'es', iso_639_2 = { b = 'spa' }, exonym = { ['eng'] = { 'Spanish', 'Castilian' }, ['fre'] = { 'espagnol', 'castillan' } } },
  ['sc'] = 'srd',
  ['srd'] = { iso_639_1 = 'sc', iso_639_2 = { b = 'srd' }, exonym = { ['eng'] = { 'Sardinian' }, ['fre'] = { 'sarde' } } },
  ['srn'] = { iso_639_2 = { b = 'srn' }, exonym = { ['eng'] = { 'Sranan Tongo' }, ['fre'] = { 'sranan tongo' } } },
  ['sr'] = 'srp',
  ['srp'] = { iso_639_1 = 'sr', iso_639_2 = { b = 'srp' }, exonym = { ['eng'] = { 'Serbian' }, ['fre'] = { 'serbe' } } },
  ['srr'] = { iso_639_2 = { b = 'srr' }, exonym = { ['eng'] = { 'Serer' }, ['fre'] = { 'sérère' } } },
  ['ssa'] = { iso_639_2 = { b = 'ssa' }, exonym = { ['eng'] = { 'Nilo-Saharan languages' }, ['fre'] = { 'nilo-sahariennes, langues' } } },
  ['ss'] = 'ssw',
  ['ssw'] = { iso_639_1 = 'ss', iso_639_2 = { b = 'ssw' }, exonym = { ['eng'] = { 'Swati' }, ['fre'] = { 'swati' } } },
  ['suk'] = { iso_639_2 = { b = 'suk' }, exonym = { ['eng'] = { 'Sukuma' }, ['fre'] = { 'sukuma' } } },
  ['su'] = 'sun',
  ['sun'] = { iso_639_1 = 'su', iso_639_2 = { b = 'sun' }, exonym = { ['eng'] = { 'Sundanese' }, ['fre'] = { 'soundanais' } } },
  ['sus'] = { iso_639_2 = { b = 'sus' }, exonym = { ['eng'] = { 'Susu' }, ['fre'] = { 'soussou' } } },
  ['sux'] = { iso_639_2 = { b = 'sux' }, exonym = { ['eng'] = { 'Sumerian' }, ['fre'] = { 'sumérien' } } },
  ['sw'] = 'swa',
  ['swa'] = { iso_639_1 = 'sw', iso_639_2 = { b = 'swa' }, exonym = { ['eng'] = { 'Swahili' }, ['fre'] = { 'swahili' } } },
  ['sv'] = 'swe',
  ['swe'] = { iso_639_1 = 'sv', iso_639_2 = { b = 'swe' }, exonym = { ['eng'] = { 'Swedish' }, ['fre'] = { 'suédois' } } },
  ['syc'] = { iso_639_2 = { b = 'syc' }, exonym = { ['eng'] = { 'Classical Syriac' }, ['fre'] = { 'syriaque classique' } } },
  ['syr'] = { iso_639_2 = { b = 'syr' }, exonym = { ['eng'] = { 'Syriac' }, ['fre'] = { 'syriaque' } } },
  ['ty'] = 'tah',
  ['tah'] = { iso_639_1 = 'ty', iso_639_2 = { b = 'tah' }, exonym = { ['eng'] = { 'Tahitian' }, ['fre'] = { 'tahitien' } } },
  ['tai'] = { iso_639_2 = { b = 'tai' }, exonym = { ['eng'] = { 'Tai languages' }, ['fre'] = { 'tai, langues' } } },
  ['ta'] = 'tam',
  ['tam'] = { iso_639_1 = 'ta', iso_639_2 = { b = 'tam' }, exonym = { ['eng'] = { 'Tamil' }, ['fre'] = { 'tamoul' } } },
  ['tt'] = 'tat',
  ['tat'] = { iso_639_1 = 'tt', iso_639_2 = { b = 'tat' }, exonym = { ['eng'] = { 'Tatar' }, ['fre'] = { 'tatar' } } },
  ['te'] = 'tel',
  ['tel'] = { iso_639_1 = 'te', iso_639_2 = { b = 'tel' }, exonym = { ['eng'] = { 'Telugu' }, ['fre'] = { 'télougou' } } },
  ['tem'] = { iso_639_2 = { b = 'tem' }, exonym = { ['eng'] = { 'Timne' }, ['fre'] = { 'temne' } } },
  ['ter'] = { iso_639_2 = { b = 'ter' }, exonym = { ['eng'] = { 'Tereno' }, ['fre'] = { 'tereno' } } },
  ['tet'] = { iso_639_2 = { b = 'tet' }, exonym = { ['eng'] = { 'Tetum' }, ['fre'] = { 'tetum' } } },
  ['tg'] = 'tgk',
  ['tgk'] = { iso_639_1 = 'tg', iso_639_2 = { b = 'tgk' }, exonym = { ['eng'] = { 'Tajik' }, ['fre'] = { 'tadjik' } } },
  ['tl'] = 'tgl',
  ['tgl'] = { iso_639_1 = 'tl', iso_639_2 = { b = 'tgl' }, exonym = { ['eng'] = { 'Tagalog' }, ['fre'] = { 'tagalog' } } },
  ['th'] = 'tha',
  ['tha'] = { iso_639_1 = 'th', iso_639_2 = { b = 'tha' }, exonym = { ['eng'] = { 'Thai' }, ['fre'] = { 'thaï' } } },
  ['bo'] = 'tib',
  ['bod'] = 'tib',
  ['tib'] = { iso_639_1 = 'bo', iso_639_2 = { b = 'tib', t = 'bod' }, exonym = { ['eng'] = { 'Tibetan' }, ['fre'] = { 'tibétain' } } },
  ['tig'] = { iso_639_2 = { b = 'tig' }, exonym = { ['eng'] = { 'Tigre' }, ['fre'] = { 'tigré' } } },
  ['ti'] = 'tir',
  ['tir'] = { iso_639_1 = 'ti', iso_639_2 = { b = 'tir' }, exonym = { ['eng'] = { 'Tigrinya' }, ['fre'] = { 'tigrigna' } } },
  ['tiv'] = { iso_639_2 = { b = 'tiv' }, exonym = { ['eng'] = { 'Tiv' }, ['fre'] = { 'tiv' } } },
  ['tkl'] = { iso_639_2 = { b = 'tkl' }, exonym = { ['eng'] = { 'Tokelau' }, ['fre'] = { 'tokelau' } } },
  ['tlh'] = { iso_639_2 = { b = 'tlh' }, exonym = { ['eng'] = { 'Klingon', 'tlhIngan-Hol' }, ['fre'] = { 'klingon' } } },
  ['tli'] = { iso_639_2 = { b = 'tli' }, exonym = { ['eng'] = { 'Tlingit' }, ['fre'] = { 'tlingit' } } },
  ['tmh'] = { iso_639_2 = { b = 'tmh' }, exonym = { ['eng'] = { 'Tamashek' }, ['fre'] = { 'tamacheq' } } },
  ['tog'] = { iso_639_2 = { b = 'tog' }, exonym = { ['eng'] = { 'Tonga (Nyasa)' }, ['fre'] = { 'tonga (Nyasa)' } } },
  ['to'] = 'ton',
  ['ton'] = { iso_639_1 = 'to', iso_639_2 = { b = 'ton' }, exonym = { ['eng'] = { 'Tonga (Tonga Islands)' }, ['fre'] = { 'tongan (Îles Tonga)' } } },
  ['tpi'] = { iso_639_2 = { b = 'tpi' }, exonym = { ['eng'] = { 'Tok Pisin' }, ['fre'] = { 'tok pisin' } } },
  ['tsi'] = { iso_639_2 = { b = 'tsi' }, exonym = { ['eng'] = { 'Tsimshian' }, ['fre'] = { 'tsimshian' } } },
  ['tn'] = 'tsn',
  ['tsn'] = { iso_639_1 = 'tn', iso_639_2 = { b = 'tsn' }, exonym = { ['eng'] = { 'Tswana' }, ['fre'] = { 'tswana' } } },
  ['ts'] = 'tso',
  ['tso'] = { iso_639_1 = 'ts', iso_639_2 = { b = 'tso' }, exonym = { ['eng'] = { 'Tsonga' }, ['fre'] = { 'tsonga' } } },
  ['tk'] = 'tuk',
  ['tuk'] = { iso_639_1 = 'tk', iso_639_2 = { b = 'tuk' }, exonym = { ['eng'] = { 'Turkmen' }, ['fre'] = { 'turkmène' } } },
  ['tum'] = { iso_639_2 = { b = 'tum' }, exonym = { ['eng'] = { 'Tumbuka' }, ['fre'] = { 'tumbuka' } } },
  ['tup'] = { iso_639_2 = { b = 'tup' }, exonym = { ['eng'] = { 'Tupi languages' }, ['fre'] = { 'tupi, langues' } } },
  ['tr'] = 'tur',
  ['tur'] = { iso_639_1 = 'tr', iso_639_2 = { b = 'tur' }, exonym = { ['eng'] = { 'Turkish' }, ['fre'] = { 'turc' } } },
  ['tut'] = { iso_639_2 = { b = 'tut' }, exonym = { ['eng'] = { 'Altaic languages' }, ['fre'] = { 'altaïques, langues' } } },
  ['tvl'] = { iso_639_2 = { b = 'tvl' }, exonym = { ['eng'] = { 'Tuvalu' }, ['fre'] = { 'tuvalu' } } },
  ['tw'] = 'twi',
  ['twi'] = { iso_639_1 = 'tw', iso_639_2 = { b = 'twi' }, exonym = { ['eng'] = { 'Twi' }, ['fre'] = { 'twi' } } },
  ['tyv'] = { iso_639_2 = { b = 'tyv' }, exonym = { ['eng'] = { 'Tuvinian' }, ['fre'] = { 'touva' } } },
  ['udm'] = { iso_639_2 = { b = 'udm' }, exonym = { ['eng'] = { 'Udmurt' }, ['fre'] = { 'oudmourte' } } },
  ['uga'] = { iso_639_2 = { b = 'uga' }, exonym = { ['eng'] = { 'Ugaritic' }, ['fre'] = { 'ougaritique' } } },
  ['ug'] = 'uig',
  ['uig'] = { iso_639_1 = 'ug', iso_639_2 = { b = 'uig' }, exonym = { ['eng'] = { 'Uighur', 'Uyghur' }, ['fre'] = { 'ouïgour' } } },
  ['uk'] = 'ukr',
  ['ukr'] = { iso_639_1 = 'uk', iso_639_2 = { b = 'ukr' }, exonym = { ['eng'] = { 'Ukrainian' }, ['fre'] = { 'ukrainien' } } },
  ['umb'] = { iso_639_2 = { b = 'umb' }, exonym = { ['eng'] = { 'Umbundu' }, ['fre'] = { 'umbundu' } } },
  ['und'] = { iso_639_2 = { b = 'und' }, exonym = { ['eng'] = { 'Undetermined' }, ['fre'] = { 'indéterminée' } } },
  ['ur'] = 'urd',
  ['urd'] = { iso_639_1 = 'ur', iso_639_2 = { b = 'urd' }, exonym = { ['eng'] = { 'Urdu' }, ['fre'] = { 'ourdou' } } },
  ['uz'] = 'uzb',
  ['uzb'] = { iso_639_1 = 'uz', iso_639_2 = { b = 'uzb' }, exonym = { ['eng'] = { 'Uzbek' }, ['fre'] = { 'ouszbek' } } },
  ['vai'] = { iso_639_2 = { b = 'vai' }, exonym = { ['eng'] = { 'Vai' }, ['fre'] = { 'vaï' } } },
  ['ve'] = 'ven',
  ['ven'] = { iso_639_1 = 've', iso_639_2 = { b = 'ven' }, exonym = { ['eng'] = { 'Venda' }, ['fre'] = { 'venda' } } },
  ['vi'] = 'vie',
  ['vie'] = { iso_639_1 = 'vi', iso_639_2 = { b = 'vie' }, exonym = { ['eng'] = { 'Vietnamese' }, ['fre'] = { 'vietnamien' } } },
  ['vo'] = 'vol',
  ['vol'] = { iso_639_1 = 'vo', iso_639_2 = { b = 'vol' }, exonym = { ['eng'] = { 'Volapük' }, ['fre'] = { 'volapük' } } },
  ['vot'] = { iso_639_2 = { b = 'vot' }, exonym = { ['eng'] = { 'Votic' }, ['fre'] = { 'vote' } } },
  ['wak'] = { iso_639_2 = { b = 'wak' }, exonym = { ['eng'] = { 'Wakashan languages' }, ['fre'] = { 'wakashanes, langues' } } },
  ['wal'] = { iso_639_2 = { b = 'wal' }, exonym = { ['eng'] = { 'Wolaitta', 'Wolaytta' }, ['fre'] = { 'wolaitta', 'wolaytta' } } },
  ['war'] = { iso_639_2 = { b = 'war' }, exonym = { ['eng'] = { 'Waray' }, ['fre'] = { 'waray' } } },
  ['was'] = { iso_639_2 = { b = 'was' }, exonym = { ['eng'] = { 'Washo' }, ['fre'] = { 'washo' } } },
  ['cy'] = 'wel',
  ['cym'] = 'wel',
  ['wel'] = { iso_639_1 = 'cy', iso_639_2 = { b = 'wel', t = 'cym' }, exonym = { ['eng'] = { 'Welsh' }, ['fre'] = { 'gallois' } } },
  ['wen'] = { iso_639_2 = { b = 'wen' }, exonym = { ['eng'] = { 'Sorbian languages' }, ['fre'] = { 'sorabes, langues' } } },
  ['wa'] = 'wln',
  ['wln'] = { iso_639_1 = 'wa', iso_639_2 = { b = 'wln' }, exonym = { ['eng'] = { 'Walloon' }, ['fre'] = { 'wallon' } } },
  ['wo'] = 'wol',
  ['wol'] = { iso_639_1 = 'wo', iso_639_2 = { b = 'wol' }, exonym = { ['eng'] = { 'Wolof' }, ['fre'] = { 'wolof' } } },
  ['xal'] = { iso_639_2 = { b = 'xal' }, exonym = { ['eng'] = { 'Kalmyk', 'Oirat' }, ['fre'] = { 'kalmouk', 'oïrat' } } },
  ['xh'] = 'xho',
  ['xho'] = { iso_639_1 = 'xh', iso_639_2 = { b = 'xho' }, exonym = { ['eng'] = { 'Xhosa' }, ['fre'] = { 'xhosa' } } },
  ['yao'] = { iso_639_2 = { b = 'yao' }, exonym = { ['eng'] = { 'Yao' }, ['fre'] = { 'yao' } } },
  ['yap'] = { iso_639_2 = { b = 'yap' }, exonym = { ['eng'] = { 'Yapese' }, ['fre'] = { 'yapois' } } },
  ['yi'] = 'yid',
  ['yid'] = { iso_639_1 = 'yi', iso_639_2 = { b = 'yid' }, exonym = { ['eng'] = { 'Yiddish' }, ['fre'] = { 'yiddish' } } },
  ['yo'] = 'yor',
  ['yor'] = { iso_639_1 = 'yo', iso_639_2 = { b = 'yor' }, exonym = { ['eng'] = { 'Yoruba' }, ['fre'] = { 'yoruba' } } },
  ['ypk'] = { iso_639_2 = { b = 'ypk' }, exonym = { ['eng'] = { 'Yupik languages' }, ['fre'] = { 'yupik, langues' } } },
  ['zap'] = { iso_639_2 = { b = 'zap' }, exonym = { ['eng'] = { 'Zapotec' }, ['fre'] = { 'zapotèque' } } },
  ['zbl'] = { iso_639_2 = { b = 'zbl' }, exonym = { ['eng'] = { 'Blissymbols', 'Blissymbolics', 'Bliss' }, ['fre'] = { 'symboles Bliss', 'Bliss' } } },
  ['zen'] = { iso_639_2 = { b = 'zen' }, exonym = { ['eng'] = { 'Zenaga' }, ['fre'] = { 'zenaga' } } },
  ['zgh'] = { iso_639_2 = { b = 'zgh' }, exonym = { ['eng'] = { 'Standard Moroccan Tamazight' }, ['fre'] = { 'amazighe standard marocain' } } },
  ['za'] = 'zha',
  ['zha'] = { iso_639_1 = 'za', iso_639_2 = { b = 'zha' }, exonym = { ['eng'] = { 'Zhuang', 'Chuang' }, ['fre'] = { 'zhuang', 'chuang' } } },
  ['znd'] = { iso_639_2 = { b = 'znd' }, exonym = { ['eng'] = { 'Zande languages' }, ['fre'] = { 'zandé, langues' } } },
  ['zu'] = 'zul',
  ['zul'] = { iso_639_1 = 'zu', iso_639_2 = { b = 'zul' }, exonym = { ['eng'] = { 'Zulu' }, ['fre'] = { 'zoulou' } } },
  ['zun'] = { iso_639_2 = { b = 'zun' }, exonym = { ['eng'] = { 'Zuni' }, ['fre'] = { 'zuni' } } },
  ['zxx'] = { iso_639_2 = { b = 'zxx' }, exonym = { ['eng'] = { 'No linguistic content', 'Not applicable' }, ['fre'] = { 'pas de contenu linguistique', 'non applicable' } } },
  ['zza'] = { iso_639_2 = { b = 'zza' }, exonym = { ['eng'] = { 'Zaza', 'Dimili', 'Dimli', 'Kirdki', 'Kirmanjki', 'Zazaki' }, ['fre'] = { 'zaza', 'dimili', 'dimli', 'kirdki', 'kirmanjki', 'zazaki' } } },

}

return data
